[workspace]
members = ["interpose-sandbox"]

[package]
name = "cargo-sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
anstream = "0.6.21"
anstyle = "1.0.13"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
cargo-test-support = "0.8.1"
snapbox = "0.6.21"

[profile.interpose-sandbox]
inherits = "release"
panic = "abort"
lto = true
strip = true
